const weaponMapping = {
    //Misc Ship status changes
    "Crash": "Ship Collision",
    //Missles & Torps
    "MRCK_S09_AEGS_Retaliator_Fore": "Argos IX Torpedo",
    "MRCK_S10_RSI_Polaris_Torpedo_rt": "S10 Polaris Torpedo",
    "MRCK_S10_RSI_Polaris_Torpedo_rb": "S10 Polaris Torpedo",
    "MRCK_S10_RSI_Polaris_Torpedo_lb": "S10 Polaris Torpedo",
    "MRCK_S10_RSI_Polaris_Torpedo_lt": "S10 Polaris Torpedo",
    "MRCK_S03_AEGS_Sabre_Firebird": "Thunderbolt III",
    "MRCK_S03_BEHR_Quad_S01": "Pioneer I",
    "MRCK_S04_BEHR_Octo_S01": "Taskforce I",
    "MRCK_S03_BEHR_Dual_S02": "S2 Missile",
    "BMBRCK_S03_BEHR_Single_S03": "S3 Thunder Ball Bomb",
    "BMBRCK_CRUS_Spirit_A1": "A1 Bomb",
    "BMBRCK_CRUS_STARL_Left": "A2 Bomb",
    "BMBRCK_CRUS_STARL_Right": "A2 Bomb",
    //Ship weapons
    "KLWE_MassDriver_S10": "Tungsten Refrigerator",
    "HRST_LaserBeam_Bespoke": "The SUN",
    "RSI_Bespoke_BallisticCannon_A": "S6 Polaris Ballistic Cannon",
    "KLWE_LaserRepeater_S1": "CF-117 Bulldog Repeater",
    "KLWE_LaserRepeater_S2": "CF-227 Badger Repeater",
    "KLWE_LaserRepeater_S3": "CF-337 Panther Repeater",
    "KLWE_LaserRepeater_S4": "CF-447 Rhino Repeater",
    "KLWE_LaserRepeater_S5": "CF-557 Galdereen Repeater",
    "KLWE_LaserRepeater_S6": "CF-667 Mammoth Repeater",
    "NONE_LaserRepeater_S1": "Ardor-1 Repeater",
    "NONE_LaserRepeater_S2": "Ardor-2 Repeater",
    "NONE_LaserRepeater_S3": "Ardor-3 Repeater",
    "HRST_LaserRepeater_S1": "Attrition-1 Repeater",
    "HRST_LaserRepeater_S2": "Attrition-2 Repeater",
    "HRST_LaserRepeater_S3": "Attrition-3 Repeater",
    "HRST_LaserRepeater_S4": "Attrition-4 Repeater",
    "HRST_LaserRepeater_S5": "Attrition-5 Repeater",
    "HRST_LaserRepeater_S6": "Attrition-6 Repeater",
    "MXOX_NeutronRepeater_S1": "S1 NDB-26 Repeater",
    "MXOX_NeutronRepeater_S2": "S2 NDB-28 Repeater",
    "MXOX_NeutronRepeater_S3": "S3 NDB-30 Repeater",
    "Krig_BallisticGatling_Bespoke_S4": "Relentless L-21 Ballistic Gatling",
    "KRON_LaserCannon_S3": "FL-33 Cannon",
    "AMRS_LaserCannon_S1": "S1 Omnisky III Cannon",
    "AMRS_LaserCannon_S2": "S2 Omnisky VI Cannon",
    "AMRS_LaserCannon_S3": "S3 Omnisky IX Cannon",
    "AMRS_LaserCannon_S4": "S4 Omnisky XII Cannon",
    "AMRS_LaserCannon_S5": "S5 Omnisky XV Cannon",
    "AMRS_LaserCannon_S6": "S6 Omnisky XVII Cannon",
    "APAR_MassDriver_S2": "Strife Mass Driver",
    "BEHR_BallisticGatling_S4": "AD4B Ballistic Gatling",
    "BEHR_BallisticGatling_S5": "AD5B Ballistic Gatling",
    "BEHR_BallisticGatling_S6": "AD6B Ballistic Gatling",
    "BEHR_LaserCannon_S3": "S3 M5A Cannon",
    "BEHR_LaserCannon_S4": "S4 M6A Cannon",
    "BEHR_LaserCannon_S5": "S5 M7A Cannon",
    "BEHR_LaserCannon_SF7E_S7": "Ion Cannon",
    "ESPR_BallisticCannon_S3": "Deadbolt III Cannon",
    "ESPR_BallisticCannon_S4": "Deadbolt IV Cannon",
    "ESPR_BallisticCannon_S5": "Deadbolt V Cannon",
    "GATS_BallisticGatling_S3": "S3 Mantis GT-220 Gatling",
    "GATS_BallisticCannon_S3": "S3 Tarantula GT-870 MkIII Cannon",
    "BEHR_BallisticGatling_Hornet_Bespoke": "MiniGun Go Burrr",
    "APAR_BallisticGatling_S4": "MinigGun Go Burrr",
    "VNCL_LaserCannon_S2": "S2 WASP Repeater",
    "VNCL_PlasmaCannon_S3": "S3 WARLORD Cannon",
    "VNCL_PlasmaCannon_S5": "S5 WRATH Cannon",
    //FPS weapons
    //Melee
    "none_melee_01": "Dropped the Soap",
    "utfl_melee_01_red01_gungame": "I WON GUN GAME",
    "utfl_melee_01_gungame": "FSK-8 Combat Knife",
    //C54 SMG
    "gmni_smg_ballistic_01": "C54 SMG",
    "gmni_smg_ballistic_01_Luminalia": "C54 Luminalia",
    "gmni_smg_ballistic_01_green_grey01": "C54 Luckbringer",
    "gmni_smg_ballistic_01_Justified": "C54 Justified",
    "gmni_smg_ballistic_01_Scorched": "C54 Scorched",
    "gmni_smg_ballistic_01_Starchaser": "C54 Starchaser",
    //P8-SC
    "behr_smg_ballistic_01": "P8-SC",
    "behr_smg_ballistic_01_white02": "P8-SC Boneyard",
    "behr_smg_ballistic_01_tan01": "P8-SC Desert Shadow",
    "behr_smg_ballistic_01_gold01": "P8-SC Executive",
    "behr_smg_ballistic_01_black01": "P8-SC Midnight",
    "behr_smg_ballistic_01_black02": "P8-SC Nightstalker",
    "behr_smg_ballistic_01_iae2201": "P8-SC Red Alert",
    "behr_smg_ballistic_01_white01": "P8-SC Stormfall",
    "behr_smg_ballistic_01_green01": "P8-SC  Warhawk",
    // P8-AR
    "behr_rifle_ballistic_02_civilian": "P8-AR",
    "behr_rifle_ballistic_01_spc_01": "P8-AR",
    "behr_rifle_ballistic_02_civilian_black01": "P8-AR",
    "behr_rifle_ballistic_02_military": "P8-AR Military",
    "behr_rifle_ballistic_02_P8SC": "P8-AR P8SC",
    "behr_rifle_ballistic_02_Scorched": "P8-AR Scorched",
    "behr_rifle_ballistic_02_Stalker": "P8-AR Stalker",
    "behr_rifle_ballistic_02_Warlord": "P8-AR Warlord",
    "behr_rifle_ballistic_02_civilian_blue01": "P8-AR CitizenCon 2954",
    // P4-AR
    "behr_rifle_ballistic_01": "P4-AR",
    "behr_rifle_ballistic_01_black02": "P4-AR Nightstalker",
    "behr_rifle_ballistic_01_green01": "P4-AR Woodland",
    "behr_rifle_ballistic_01_red01": "P4-AR Red Alert",
    "behr_rifle_ballistic_01_white01": "P4-AR Arctic",
    "behr_rifle_ballistic_01_yellow01": "P4-AR Desert Strike",
    //Karna Rifle
    "ksar_rifle_energy_01": "Karna Rifle",
    "ksar_rifle_energy_01_pink_red01": "Hello Kitty Karna",
    "ksar_rifle_energy_01_red01": "Karna Brimstone Rifle",
    "ksar_rifle_energy_01_black01": "Karna Blackout Rifle",
    "ksar_rifle_energy_01_blue_gold": "Karna Valor Rifle",
    "ksar_rifle_energy_01_blue_gold_spc_01": "Karna Valor Rifle",
    "ksar_rifle_energy_01_iae2023": "Karna Ascension Rifle",
    "ksar_rifle_energy_01_firerats01_spc": "Karna Scorched Rifle",
    "ksar_rifle_energy_01_red_green01": "Karna Christmas Rifle",
    // FS-9 LMG
    "behr_lmg_ballistic_01": "FS-9",
    "behr_lmg_ballistic_01_yellow_grey01": "FS-9 Yellow",
    "behr_lmg_ballistic_01_green01": "FS-9 Woodland",
    "behr_lmg_ballistic_01_black01": "FS-9 Nightstalker",
    "behr_lmg_ballistic_01_red01": "FS-9 Inferno",
    "behr_lmg_ballistic_01_blue01": "FS-9 Oceanic",
    "behr_lmg_ballistic_01_xenothreat01": "FS-9 Stoneface",
    //Demeco LMG
    "klwe_lmg_energy_01": "Demeco LMG",
    "klwe_lmg_energy_01_purple_blue01": "Demeco Purple LMG",
    "klwe_lmg_energy_01_iae2201": "Demeco IAE LMG",
    //F55 LMG
    "gmni_lmg_ballistic_01_blue_gold": "F55 LMG",
    "gmni_lmg_ballistic_01": "F55 LMG",
    "gmni_lmg_ballistic_01_green_red01": "Christmas F55 LMG",
    "gmni_lmg_ballistic_01_firerats01": "Scorched F55 LMG",
    //Devastator Shotgun
    "ksar_shotgun_energy_01_gold01": "Devastator Executive Shotgun",
    "ksar_shotgun_energy_01": "Devastator Shotgun",
    //S71 Rifle
    "gmni_rifle_ballistic_01": "S71 Rifle",
    "gmni_rifle_ballistic_01_firerats01": "S71 Bullseye",
    //Pistols
    "gmni_pistol_ballistic_01": "LH86 Pistol",
    "gmni_pistol_ballistic_01_blue_white01": "LH86 Pistol Permafrost",
    "gmni_pistol_ballistic_01_green01": "LH86 Green",
    "behr_pistol_ballistic_01": "S-38 Pistol",
    "ksar_pistol_ballistic_01": "Coda Revolver",
    "hdgw_pistol_ballistic_01": "Salvo Frag Pistol",
    "hdgw_pistol_ballistic_01_engraved01": "Salvo Saeed Frag Pistol",
    "klwe_pistol_energy_01": "Arclight pistol",
    "lbco_pistol_energy_01": "Yurabrev Pistol",
    //Lazer Weapons
    "volt_smg_energy_01": "Quartz Energy SMG",
    "volt_smg_energy_01_tint02": "Quartz Energy SMG",
    "volt_smg_energy_01_store02": "Quartz Clawed Steel Energy SMG",
    "volt_rifle_energy_01": "Volt Parallax Rifle",
    "volt_rifle_energy_01_tint02": "Volt Parallax Rifle",
    "volt_rifle_energy_01_camo01": "Volt Parallax Shock Trooper Rifle",
    "volt_rifle_energy_01_black_gold01": "Volt Parallax Downburst Rifle",
    "volt_shotgun_energy_01_tint01": "Volt Parallax Shotgun",
    "volt_shotgun_energy_01": "Volt Parallax Shotgun",
    "volt_shotgun_energy_01_tint03": "Volt Parallax Shotgun",
    "volt_smg_energy_01_store01": "Quartz True Valor Energy SMG",
    "volt_sniper_energy_01_tint02":"Zenith Laser Sniper Rifle",
    "volt_lmg_energy_01_tint02": "Volt Fresnel LMG",
    //BR-2
    "behr_shotgun_ballistic_01": "BR-2 Shotgun",
    //Gallant Rifle
    "klwe_rifle_energy_01": "Gallant Rifle",
    "klwe_rifle_energy_01_green01": "Gallant Scrubland",
    "klwe_rifle_energy_01_black01": "Gallant Midnight",
    //Lumin V
    "klwe_smg_energy_01_blue_gold": "Lumin V Invictus SMG",
    "klwe_smg_energy_01": "Lumin V",
    //R97 Shotgun
    "gmni_shotgun_ballistic_01_pink_red01": "R97 RedAlert Shotgun",
    "gmni_shotgun_ballistic_01": "R97 Shotgun",
    //P6-LR
    "behr_sniper_ballistic_01": "P6-LR ",
    "behr_sniper_ballistic_01_black01": "P6-LR Black",
    "behr_sniper_ballistic_01_arctic01": "P6-LR Rime",
    //Scalpel Sniper
    "ksar_sniper_ballistic_01": "Scalpel Sniper",
    "ksar_sniper_ballistic_01_white_blue_01": "Scalpel Permafrost Sniper",
    //A03 Rifle
    "gmni_sniper_ballistic_01": "AO3 Rifle",
    "gmni_sniper_ballistic_01_iae2201": "A03 Red Alert Rifle",
    "gmni_sniper_ballistic_01_firerats01": "A03 Scorched Rifle",
    //Grenade Launcher
    "behr_glauncher_ballistic_01": "Grenade Launcher",
    //Ravager Shotgun
    "ksar_shotgun_ballistic_01": "Ravager Shotgun",
    //Custodian SMG
    "ksar_smg_energy_01": "Custodian SMG",
    "ksar_smg_energy_01_black01": "Custodian SMG",
    //Deadrig Shotgun
    "none_shotgun_ballistic_01": "Deadrig shotgun (maybe?)",
    //Tank Weapons
    "HRST_Nova_BallisticCannon_S5": "Kentucky windage",
    "HRST_Storm_LaserRepeater_S3": "Pee Shooter",
    //Special Weapons
    "apar_special_ballistic_01": "Railgun",
    "apar_special_ballistic_02": "Animus Missile Launcher"
};

const shipMapping = {
    //Ground Zones
    "p2l4_contestedzone": "Contested Zone",
    "ab_pyro_int_dung":"Security Keycard Zone Interior",
    "OOC_Stanton_2a_Cellin":"Security Post Kareah",
    "rs_opendungeon_rund":"Ruin Contested Zone Ghost Arena",
    "p5l2_contestedzone": "Contested Zone",
    "OOC_Stanton_2c_Yela":"Yela",
    "P3_L5":"PYAM-SUPVISR-3-5",
    "ab_pyro_int_dung_exec":"Excectutive Hangers",
    "rs_cz_rewards":"CZ Loot Room",
    "orbtl_002_plat_001_util_a_orbital_001_occu_a_final":"Hathor OLP",
    "asd_labresearch_int_01a":"Lazarus Complex",
    "ht_xs_003_occu_a_final_int_b-001":"Lazarus Complex",
    "t_xs_003_occu_a_final_int_b-002":"Lazarus Complex",
    "ht_xs_003_occu_a_final_int_b-003":"Lazarus Complex",
    "ht_xs_003_occu_a_final_int_b-004":"Lazarus Complex",
    "ht_station_001_occu_a_final_int":"Lazarus Complex",
    "ht_xs_003_occu_a_final_int_b":"Lazarus Complex",
    "TransitCarriage_ASD_Shuttle_A":"Lazarus Shuttle",
    "asd_labdata_int_01a":"Farro Data Center",
    "OC_Nose_med_sfce_ctpl_g":"Caterpillar Wreck",
    "OOC_Stanton_4_Microtech":"Microtech",
    "OOC_Stanton_1a_Ariel":"Arial",
    "layout_int_power":"ASD Facilities",
    "OOC_Stanton_1_Hurston":"Dupree Industrial Manufacturing Facility",
    //Ship Components
    "POWR_TYDT_S01_Slipstream_SCItem":"Slipstream OP",
    //Prison
    "ObjectContainer-0002_INT": "Prison",
    //Station
    "TransitCarriage_Reststop_Small":"Elevator Combat",
    "Hangar_MediumFront_RestStop_Pyro":"Hanger PVP",
    "Hangar_SmallFront_RestStop_Pyro":"Hanger PVP",
    "Hangar_LargeTop_RestStop_Pyro": "Hanger PVP",
    "Hangar_XLTop_Lorville":"Hanger PVP",
    "rs_int_p3l1":"Starlight Station PVP",
    "Hangar_SmallFront_GrimHEX":"GrimHex Small Hanger PVP",
    "util_a_orbital_001_occu_a_final-001":"OLP PVP",
    "OOC_Stanton_2b_Daymar": "Daymar PVP",
    "TransitCarriage_elev_util":"Elevator PVP",
    "Hangar_LargeFront_GrimHEX":"GrimHex Large Hanger PVP",
    "Hangar_XLTop_Orison":"Orison Hanger PVP",
    //Plannet Locations
    "util_dish_001_rund_a_final_int": "Hathor Ground Station",
    "util_a_orbital_001_occu_a_final_int": "Hathor Orbital Station",
    "util_cmpd_wrhse_lge_001_rund_c_final_int": "Hathor Large Warehouse",
    "util_cmpd_wrhse_sml_001_rund_c_final_int": "Hathor Small Warehouse",
    "util_cmpd_wrhse_lge_001_rund_a_final_int": "Hathor Warehouse",
    "RastarInteriorGridHost": "Outpost Buildings",
    "OOC_Stanton_2_Crusader": "Crusader System",
    "OOC_Stanton_1b_Aberdeen": "Aberdeen",
    "sand01_vlk_001_001_int": "Valakkar Cave",
    //AEGIS
    "AEGS_Avenger_Stalker": "Avenger Stalker",
    "AEGS_Avenger_Titan": "Avenger Titan",
    "AEGS_Eclipse": "Eclipse",
    "AEGS_Gladius": "Gladius",
    "AEGS_Gladius_PIR": "Gladius Pirate",
    "AEGS_Gladius_Valiant": "Gladius Valiant",
    "AEGS_Hammerhead": "Hammerhead",
    "AEGS_Redeemer": "Redeemer",
    "AEGS_Retaliator": "Retaliator",
    "AEGS_Sabre": "Sabre",
    "AEGS_Sabre_Comet": "Sabre Comet",
    "AEGS_Sabre_Firebird": "Sabre Firebird",
    "AEGS_Sabre_Raven": "Sabre Raven",
    "AEGS_Vanguard_Harbinger": "Vanguard Harbinger",
    "AEGS_Vanguard_Sentinel": "Vanguard Sentinel",
    "AEGS_Vanguard_Hoplite": "Vanguard Hoplight",
    "AEGS_Reclaimer":"Dog Microwaver",
    "AEGS_Reclaimer_Showdown":"Dog Microwaver BIS",
    "AEGS_Idris_P": "Idris-Peacekeeper",
    "TransitCarriage_AEGS_Idris_Cargo_Elevator" : "Idris-P Interior",
    //ANVIL
    "ANVL_Arrow": "Arrow",
    "ANVL_C8X_Pisces_Expedition": "C8X Pisces Expedition",
    "ANVL_C8R_Pisces":"C8R Pisces",
    "ANVL_C8_Pisces":"C8 Pisces",
    "ANVL_C8_Pisces_Tutorial":"C8 Pisces Tutorial",
    "ANVL_Terrapin_Medic":"Terrapin Medic",
    "ANVL_Terrapin":"Terrapin",
    "ANVL_Carrack": "Carrack",
    "ANVL_Ballista": "Ballista",
    "ANVL_Carrack_Expedition": "Carrack Expedition",
    "ANVL_Hornet_F7A_Mk1": "F7C-M Super Hornet Mk I",
    "ANVL_Hornet_F7CM": "F7C-M Super Hornet Mk I",
    "ANVL_Hornet_F7C_Mk2": "Hornet F7C MKII",
    "ANVL_Hornet_F7A_Mk2": "Hornet F7A MKII",
    "ANVL_Hornet_F7CR_Mk2": "Hornet F7C MKII",
    "ANVL_Hornet_F7CM_Mk2":"Hornet F7CM MKII",
    "ANVL_Hornet_F7CM_Heartseeker": "Hornet F7CM Heartseeker MKI",
    "ANVL_Hornet_F7A_Mk2_Exec_Stealth":"Hornet F7A MKII Exectutive Stealth Build",
    "ANVL_Hornet_F7A_Mk2_Exec_Military":"Hornet F7A MKII Excectutive Military Build",
    "ANVL_Hornet_F7C_Wildfire":"F7C Hornet MKI Wildfire ",
    "ANVL_Hornet_F7CS_Mk1": "Hornet F7CS MKI Ghost",
    "ANVL_Hornet_F7CS_Mk2": "Hornet F7CS MKII Ghost",
    "ANVL_Hornet_F7CS": "Hornet F7C-S MKI Ghost ",
    "ANVL_Lightning_F8C": "F8C Lightning",
    "ANVL_Lightning_F8C_Exec":"F8C Lightning Executive",
    "ANVL_Lightning_F8C_Exec_Stealth": "F8C Lighting Executive Stealth",
    "ANVL_Gladiator":"Gladiator",
    "ANVL_Valkyrie": "Valkyrie",
    "ANVL_Hawk": "Hawk",
    "ANVL_Hurricane": "Hurricane",
    "ANVL_Asgard":"Asgard",
    //AOPOA
    "XNAA_SanTokYai": "Teriyaki",
    "XIAN_Scout":"Khartu-al",
    //ARGO
    "ARGO_RAFT": "Argo Raft",
    //BANU
    "BANU_Defender": "Banu Defender",
    //CONSOLIDATED OUTLAND
    "CNOU_Mustang_Alpha": "Mustang Alpha",
    "CNOU_Mustang_Delta":"Mustang Delta",
    "CNOU_Nomad": "Nomad",
    //CRUSADER
    "CRUS_Spirit_A1": "Spirit A1",
    "CRUS_Starlifter_A2": "Hercules A2",
    "CRUS_Starfighter_Inferno": "Ares Inferno",
    "CRUS_Starfighter_Ion":"Ares Ion",
    "CRUS_Starfighter_Ino": "Ares Ion",
    "CRUS_Spirit_C1": "Spirit C1",
    "CRUS_Starlifter_C2": "Hercules C2",
    "CRUS_Intrepid": "Intredpid",
    "CRUS_Starlifter_M2": "Hercules M2",
    "CRUS_Star_Runner": "Mercury Star Runner",
    //DRAKE
    "DRAK_Buccaneer": "Buccaneer",
    "DRAK_Caterpillar": "Caterpillar",
    "DRAK_Caterpillar_Pirate": "Caterpillar Pirate",
    "DRAK_Corsair": "Corsair",
    "DRAK_Corsair_Exec_Military":"Corsair Excectutive Miltary Build",
    "DRAK_Cutlass_Black": "Cutlass Black",
    "DRAK_Cutlass_Blue": "Cutlass Blue",
    "DRAK_Cutlass_Red": "Cutlass Red",
    "DRAK_Cutlass_Steel": "Cutlass Steel",
    "DRAK_Cutlass_Black_Exec_Military":"Cutlass Black Excectutive Military Build",
    "DRAK_Cutlass_Black_Exec_Stealth":"Cutlass Black Excectutive Stealth Build",
    "DRAK_Cutlass_Black_ShipShowdown":"Cutlass Black BIS",
    "DRAK_Cutter": "Cutter",
    "DRAK_Cutter_Rambler": "Cutter Rambler",
    "DRAK_Cutter_Scout": "Cutter Scout",
    "DRAK_Vulture": "Vulture",
    "DRAK_Herald": "Herald",
    "DRAK_Golem":"Golem",
    //ESPERIA
    "ESPR_Talon": "Talon",
    "ESPR_Prowler_Utility":"Prowler Utility",
    "ESPR_Prowler":"Prowler",
    "VNCL_Glaive":"Glaive(Replica)",
    //GATAC
    "GAMA_Syulen": "Syulen",
    "GAMA_Syulen_Exec_Stealth":"Syulen Excectutive Stealth Build",
    //KRUGER
    "KRIG_P52_Merlin": "P52 Merlin",
    "KRIG_P72_Archimedes": "P72 Archimedes",
    "KRIG_L21_Wolf":"L-21 Wolf",
    //MIRAI
    "MISC_Fury": "Fury",
    "MRAI_Pulse": "Pulse",
    "MRAI_Guardian": "Guardian",
    "MRAI_Guardian_military": "Guardian Vault Spec",
    "MRAI_Guardian_QI": "Guardian QI",
    "MRAI_Guardian_MX": "Guardian MX",
    //MISC
    "MISC_Freelancer": "Freelancer",
    "MISC_Freelancer_MAX": "Freelancer Max",
    "MISC_Freelancer_DUR":"Freelancer DUR",
    "MISC_Hull_A": "Hull A",
    "MISC_Hull_C": "Hull C",
    "MISC_Prospector": "Prospector",
    "MISC_Reliant_Tana": "Reliant Tana",
    "MISC_Starlancer_Max": "Starlancer Max",
    "MISC_Razor_EX":"Razor EX",
    "MISC_Starfarer":"Starfarer",
    "MISC_Reliant": "Reliant",
    //ORIGIN
    "ORIG_m50":"M50",
    "ORIG_300i": "300I",
    "ORIG_315p": "315P",
    "ORIG_125a": "125A",
    "ORIG_400i": "400I",
    "ORIG_600i_Touring": "600I Touring",
    "ORIG_X1_Force": "X1 Force",
    "ORIG_890Jump":"890 Jump Mr MoneyBags",
    //RSI
    "RSI_Aurora_CL": "Aurora CL",
    "RSI_Aurora_ES": "Aurora ES",
    "RSI_Aurora_LN": "Aurora LN",
    "RSI_Aurora_LX": "Aurora LX",
    "RSI_Aurora_MR": "Aurora MR",
    "RSI_Constellation_Andromeda":"Constellation Andromeda",
    "RSI_Constellation_Aquila":"Constellation Aquila",
    "RSI_Constellation_Taurus":"Constellation Taurus",
    "RSI_Constellation_Phoenix":"Constellation Phoenix",
    "RSI_Constellation_Phoenix_Emerald":"Constellation Phoenix Emerald",
    "RSI_Constellation_Taurus_military":"Constellation Taurus Vault Spec",
    "RSI_Mantis": "Mantis",
    "RSI_Ursa_Medivac": "Ursa Medivac",
    "RSI_Polaris": "Polaris",
    "RSI_Com_TP": "Polaris",
    "RSI_Polaris_Collector_Military": "Polaris Wikelo",
    "RSI_Scorpius": "Scorpius",
    "RSI_Scorpius_Antares": "Scorpius Antares",
    "rsi_scorpius_militarty":"Scorpius Vault Spec",
    "RSI_Zeus_CL": "Zeus CL",
    "RSI_Zeus_ES": "Zeus ES",
    "RSI_Meteor":"Meteor",
    //Agro
    "ARGO_MOLE": "Mole",
    //Vanduul
    "VNCL_Scythe_EA_AI_VAN_Alpha":"Vanduul Scythe",
    "VNCL_Scythe":"Vanduul Scythe",
    "VNCL_Blade":"Blade",
    //Tumblr
    "TMBL_Storm":"Storm 'Smol' Tonk",
    "TMBL_Nova":"Nova 'Thick' Tonk"
};

const ignoredVictimRules = [
    { type: 'substring', value: 'kopion' },
    { type: 'substring', value: 'marok' },
    { type: 'substring', value: 'PU_Human' },
    { type: 'substring', value: 'PC_Archetypes' },
    { type: 'substring', value: 'PU_Pilots' },
    { type: 'startsWith', value: 'quasigrazer' },
    { type: 'startsWith', value: 'shipjacker' },
    { type: 'startsWith', value: 'argo_atls' },
    { type: 'regex', value: '^vlk(?!_apex_)' }
];